$RNFirebaseAnalyticsWithoutAdIdSupport=true

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'

# def __apply_Xcode_14_3_RC_post_install_workaround(installer)
#   installer.pods_project.targets.each do |target|
#     target.build_configurations.each do |config|
#       config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = "arm64"
#       current_target = config.build_settings['IPHONEOS_DEPLOYMENT_TARGET']
#       minimum_target = min_ios_version_supported
#       if current_target.to_f < minimum_target.to_f
#         config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = minimum_target
#       end
#     end
#   end
# end

def __xcode_15_workaround(installer)
  xcode_version_output = `xcodebuild -version`
  xcode_version_match = xcode_version_output.match(/Xcode (\d+(\.\d+)?)/)

  if xcode_version_match
    xcode_version = Gem::Version.new(xcode_version_match[1])
    if xcode_version >= Gem::Version.new('15.0')
      installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', '_LIBCPP_ENABLE_CXX17_REMOVED_UNARY_BINARY_FUNCTION']
        end
      end
    end
  end
end

target 'SovrynMobile' do
  config = use_native_modules!

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  target 'SovrynMobileTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
    # __apply_Xcode_14_3_RC_post_install_workaround(installer)
    __xcode_15_workaround(installer)
    installer.pods_project.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
  end
end
